ERR_ARGV = "ERROR: el número de argumentos es inválido"
ERR_FORMATO = "ERROR: formato de comando incorrecto"
ERR_PARAMS = "ERROR: cantidad de parámetros inválida para comando '{}'"
ERR_CMD = "ERROR: no existe el comando '{}'"
ERR_CAMINO = "No se encontro recorrido"
ERR_CICLO = "No se encontro ciclo para esta página"
ERR_CONEC = "No se encontro conectividad para esta página"
ERR_LECTURA = "No existe forma de leer las paginas en orden"

MENSAJE_INDEX_ERROR = "El vértice no pertenece al grafo."
